[package]
name = "no_where_to_run"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.24"
macroquad-particles = "0.1.1"
rand = "0.8.5"

[profile.dev.package.'*']
opt-level = 3